### PR TITLE
Update Go version and migrate to Go modules

### PR DESCRIPTION
**Pull request by kashyap-splunk**
Includes below changes:
- Migrate to Go modules from Glide
- Upgrade Go version to 1.17
- Update Circle CI to use Go 1.17 and Go modules
- Update readme for above changes
- Switched to '[bbolt (1.3.6)](https://github.com/etcd-io/bbolt)' from 'bolt' for the cache module due to race test issue with 'bolt' ([this](https://github.com/etcd-io/bbolt/issues/187) for reference)

Let me know if I missed anything

### CODE REVIEW

**Comment by luckyj5** [comment]
Do we need the vendor folder?

**Comment by kashyap-splunk** [comment]
> Do we need the vendor folder?

Vendor folder can help building without network access or having faster builds, both during development and in CI/CD pipelines. But we can remove it if this was not the original intention of keeping the vendor folder earlier.

**Comment by luckyj5** [comment]
> > Do we need the vendor folder?
> 
> Vendor folder can help building without network access or having faster builds, both during development and in CI/CD pipelines. But we can remove it if this was not the original intention of keeping the vendor folder earlier.

Yeah, the original intent was to be able to run it when restrictive network access. I was thinking of cleaning it up here since it anyways will be packaged in the tile. For now, let's leave it. Thanks!

**Review by luckyj5 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
