### PR TITLE
splunk nozzle now doesn't block, won't disconnect for being slow

### PR DESCRIPTION
**Pull request by Benjamintf1**

### CODE REVIEW

**Comment by Benjamintf1** [comment]
(I think generally you'll be safer if the dropping buffer is as close to and with as little code in between it and the read call, but IIRC it looked fine, but made the requested changes)

As for "having it be an option", if the nozzle blocks, those envelopes are getting dropped one way or another, there's no "not dropping" option, you're only forcing those envelopes to drop at the doppler due to the nozzle being unable to deliver the envelopes fast enough.

**Comment by Benjamintf1** [comment]
https://github.com/cloudfoundry-community/splunk-firehose-nozzle/issues/285

**Comment by Benjamintf1** [comment]
Spent some time looking at this a bit more, this pr is actually not sufficient. Blocking *could* occur here https://github.com/cloudfoundry-community/splunk-firehose-nozzle/blob/ecf9398cfbe3ce83e0252b05fa469937bf80b852/eventrouter/default.go#L67-L68.

**Comment by kashyap-splunk** [comment]
Hi @Benjamintf1 I get your point. I am trying to think of way to free the main thread to receive the next event immediately after receiving the current event from the doppler. For example, starting a separate Goroutine to route the event in [this](https://github.com/cloudfoundry-community/splunk-firehose-nozzle/blob/develop/nozzle/nozzle.go#L69) line and then either limit the Goroutines count (Bounded parallelism) or fix wait time before dropping the events.

Let me know your thoughts.

**Comment by Benjamintf1** [comment]
No, both of those will still allow promulgation of backpressure at not 100% cpu.

**Comment by Benjamintf1** [comment]
I can leave more context in the issue, I think we may have alternative or changed prs.

**Comment by Benjamintf1** [comment]
(as a short note on shortening timeouts. 1000 logs per second is 1 log per millisecond. If the processing is too slow, eventually the buffer will fill up, and a even a extremely slow 10ms timeout is 10 lost logs, 5 seconds is 50,000, that's 5 full doppler buffers. Even if we reduce that by a factor of 5, a slow nozzle will have dropped 10,000 logs on doppler for being unable to read before it reports the one metric it tried to send downstream)

**Comment by Benjamintf1** [comment]
Actually, based on concerns I'm hearing about capi. I'm going to close this in favor of saying I'd highly suggest a solution that looks more like the first pr. Or a merging of the two. I can make a new pr if wanted.

**Pull request closed without merging**
