### PR TITLE
Prevent splunk nozzle from disconnecting due to being a slow consumer

### PR DESCRIPTION
**Pull request by Benjamintf1**
add threads for posting to splunk(10 per instance), add buffered channel, and drop if the buffer is full. Report on drops every 1000 drops. 

Also, use go mod.

### CODE REVIEW

**Comment by Benjamintf1** [comment]
Looks like we might need some ci changes as well if we want to merge this. LMK if you want me to do more.

**Comment by kashyap-splunk** [comment]
Hi @Benjamintf1, thank you for working on this. So the HEC-writers are already threaded (configurable number of goroutines) and the channel before them also has configurable size of buffer. Let me know if you think still threading/buffer needs to be added.

To avoid disconnect due to slow consumer, we can add event dropping at sink level ([line](https://github.com/cloudfoundry-community/splunk-firehose-nozzle/blob/ecf9398cfbe3ce83e0252b05fa469937bf80b852/eventsink/splunk.go#L81)). We will add a configuration for this. So the sink will drop events if configured, in case the buffer/workers are not enough to catch-up.

Also, please raise pull-requests for develop branch instead of master.

**Comment by Benjamintf1** [comment]
Yeah, adding dropping is the key thing. It'd be fine if that happens on the sink level as long as no possibly blocking, or computational expensive steps happen between the receive and the putting in the channel there.

**Comment by Benjamintf1** [comment]
looks like someone else already made a better pr wrt go mod!!!(Exciting!) https://github.com/cloudfoundry-community/splunk-firehose-nozzle/pull/283

**Comment by Benjamintf1** [comment]
(I'd prefer it to be default, or at the very least, for it to log when it hits the buffer limit)

**Pull request closed without merging**
