### PR TITLE
Bump up the default timeout value for keepalive since when logaggrator

### PR DESCRIPTION
**Pull request by chenziliang**
is busy, it may come back to client in 25 seconds
	modified:   Makefile
	modified:   main.go

### CODE REVIEW

**Comment by chenziliang** [comment]
When Firehose server is busy, it probably can't reach back to client in 25 seconds, this is why we still see policy violation error in issue #36

**Comment by cholick** [comment]
Some of these comments aren't actually related to this PR, I just missed a change to the `.gitignore` file in #19 that changed files this commit touches.

There is Go code checked in to `vendor`, but `.gitignore` has the `vendor` directory ignored. This is wrong.

The vendor folder should be checked in and not ignored. Glide's job is to manage the contents of that folder, not fetch it every time on a clean checkout.

The makefile install deps shouldn't have 2 installs, it should just be 

```
 installdeps:
  	glide --debug install --strip-vendor
```

`installdeps` also shouldn't be part of the default make target. It's an edge case that's only invoked when dependencies are updated, to get the new versions in to the `vendor` folder.

Alternately (and I do think this choice has more disadvantages), push a commit that removes all the contents of the `vendor` folder and rely on Glide to always get code. Having that both checked in and ignored is a bad state.

**Comment by chenziliang** [comment]
@cholick Thanks. 
1. Installdpes should have one install. Will fix this.
2. vendor folder checkin. I was not noticing vendor folder has been checked in. Personally when i start a go project, I prefer to not checkin the vendor folder since glide is supposed to do the job.  But there are cases i think we need consider: 
a. nozzle-release currently will not do glide install to install the dependency i guess, we probably need fix splunk nozzle release to do a full make after checking out the splunk nozzle code, which does everything. 
Having said my preference, i do think it is good let's keep the vendor folder checkin for now and fix .gitignore
b. the dependent libs are gone which are supposed to never happen.

**Comment by cholick** [comment]
One other thing to keep in mind is the BOSH release. Even in an internet connected environment, the compilation VMS might not necessarily be able to reach out. So for the BOSH release, it's definitely better to have everything present when possible.

**Comment by psychickita** [comment]
@cholick @chenziliang - guys, with this topic in mind, we should figure out what to do with this PR: https://github.com/cloudfoundry-community/splunk-firehose-nozzle/pull/41 (still needs approval)
it includes changes to syslog nozzle that I was not able to commit to the syslog repo. 
I understand this is a bad state, so our options are:

- use the syslog libraries as part of our project (move them out of vendor and modify at will)
- duplicate any syslog code that requires adjustment in our project
- work around syslog limitation by implementing a different solution

What are your thoughts?

**Comment by chenziliang** [comment]
My thought is for enriching SPLUNK events by using extra fields, it should be done in Splunk Nozzle which is option 3 although in sys log has similar idea/code, but it needs to be revised for specific Splunk case. This is why they don't agree merge our changes to sys log repo.

Personally I don't think it is a super complex changes in Splunk nozzle. Maybe several lines can get it done.

For now, I didn't see it is urgent or we have a strong reason to duplicate sys log into Splunk nozzle repo. It doesn't necessarily mean we shouldn't do this forever since depending on another nozzle seems not elegant and if in future we have more reasonable changes to sys log which still can not merge into its repo, we can start doing the dup and modifications.

**Pull request merged**
