### PR TITLE
Fix race condition errors reported by go test -race

### PR DESCRIPTION
**Pull request by chenziliang**
modified:   drain/logging_splunk.go
	modified:   drain/logging_splunk_test.go
	modified:   sink/splunk_sink_test.go
	modified:   testing/mocks.go

### CODE REVIEW

**Comment by chenziliang** [comment]
We have 2 data race conditions in the code. Eliminate them. The report from  **go test -race** now is good.
`kchen@splunk splunk-firehose-nozzle (bugfix/race-conditions)$go test -race `go list ./... | grep -v vendor`
?       github.com/cloudfoundry-community/splunk-firehose-nozzle        [no test files]
ok      github.com/cloudfoundry-community/splunk-firehose-nozzle/auth   1.470s
ok      github.com/cloudfoundry-community/splunk-firehose-nozzle/drain  1.675s
?       github.com/cloudfoundry-community/splunk-firehose-nozzle/firehoseclient [no test files]
ok      github.com/cloudfoundry-community/splunk-firehose-nozzle/sink   1.435s
ok      github.com/cloudfoundry-community/splunk-firehose-nozzle/splunk 1.467s
?       github.com/cloudfoundry-community/splunk-firehose-nozzle/testing        [no test files]`

**Comment by cholick** [comment]
Is the second flush condition to Splunk to address a cap (either payload size or count) on the POST to Splunk? Seems like a good change, it's just not related to the stated reason for the PR. You have a FIXME to make this configurable, but I don't think that's needed. I would suggest a larger value than `50` though.

**Comment by cholick** [comment]
By changing `l.logger.Fatal` to `l.logger.Error`, you're potentially hiding a condition where the app will *never* succeed talking to Splunk (misconfigured) and will instead run until crashing due to resource constraints (`batch` grows unbounded). While `Fatal` wasn't a great choice (especially in contexts outside splunk-firehose-nozzle-release with its co-located forwarder), I do think there needs to be some an earlier "give up" condition.

**Comment by cholick** [comment]
Asking the operator to tune the events channel size:
```
// FIXME, make buffer size 100 configurable
events: make(chan map[string]interface{}, 100),
```
concerns me a bit (in that the operator needs a whole lot of context to choose a good number). The only time the buffer in this channel is really used is during however long the post to Splunk takes. Just choose a really large value (1000) and call it good?

**Comment by stinkingpig** [comment]
I'm good with a default value that's pulled from guesswork, but hard-coded defaults in code is suboptimal.

**Comment by chenziliang** [comment]
@cholick First thanks very much for the comments.
1) log.Fatal, i think we should change it to log.Error since the previous one crash the Nozzle. By this new fix, an event chan which has default size 100 (hard coded one for now) has been introduced which will block more events flowing in if there is network chokes or HFW HEC issue downstream. So it will not cause memory issue (grow infinitely
2) I make a comment "FIXME" for the event queue size, because i will send out another enhancement PR which will allow user pass in a param called say "queue_size" to make it configurable when running Splunk CF Nozzle. @stinkingpig after testing we will make it a reasonable default value which we don't have so far. This is why "FIXME"
3) The second Flush condition is we reach a timeout. It is best we batch events to HEC which really cap the performance of the injection. So the changes is either we reach a good batch (50 events) or a timedout (1 second for example, should be configurable again), we did the flush.

**Comment by cholick** [comment]
Feel free to ignore any of my feedback and merge when you're happy. I don't have any other thoughts to add.

**Pull request merged**
