### PR TITLE
Feature/issue8 index routing

### PR DESCRIPTION
**Pull request by chenziliang**

### CODE REVIEW

**Comment by chenziliang** [comment]
1. This PR supports routing events to different index according to app name, space name or org name. All names can be regex.
The priority of index routing:  app overrides space which overrides org which overrides default. It also means the index set on app will be examined first and then space and then org

2. End user's index routing configuration will loolk like
```
{                                                                               
	"defult_index": "main",                                                      
	"mappings": {                                                                
		"cf_org_name": [{"value": "sales.*", "index": "sales"}, ...],              
		"cf_space_name": [{"value": "test.*", "index": "test"}, ...],              
		"cf_app_name": [{"value": "fin.*", "index": "financial"}, {"value": "stage.*", "index": nil}, ...]
	}                                                                            
} 
```

3. In this PR, we don't support index routing by examining raw logs.

**Comment by chenziliang** [comment]
All unit test and integration tests have been run. And newly added code is almost 100 % line covered.

Screenshots for integration testing:
screen shot 2017-07-22 at 11 45 01 pm

**Comment by chenziliang** [comment]
My testing index mapping configuration looks like below:
```
{
  "default_index": "otherindex",
  "mappings": {
    "cf_org_name": [
      {
        "value": "kchen.*",
        "index": "orgindex"
      }
    ],
    "cf_space_name": [
      {
        "value": "pcf.*",
        "index": "spaceindex"
      }
    ],
    "cf_app_name": [
      {
        "value": "app.*",
        "index": "appindex"
      }
    ]
  }
}
```

**Comment by cholick** [comment]
Org, space, and app name are all mutable. I don't think that's the right choice (versus id).

The config implicitly toggles `AddAppInfo` to true, which I don't believe is the right
behavior. `AddAppInfo` to false + name based index routing is a bad state, I don't think
turning it on is the right choice to make on the user's behalf. Maybe they don't want 
all that additional load on the API server? To me, this means the user has given us conflicting signals that should be resolved, rather than us weighing one choice over the other.

You're also requiring index mapping for the default index:
```{"default_index":"main"}`
as in, people running the nozzle have to input json into an environment variable. This
is a bit hostile to people who don't care about this feature. You're forcing them
to input valid json into a config value. In the tile situation, there is no
ability to validate the json. An error here is 30+ minutes before feedback that the json
isn't correct. The original config option of string based default index (with the json
structure overriding). All existing users will also have to modify their configs.

This also changes the behavior for empty index. Previously, the events would go 
wherever the http event collector default was. Now these events are getting
discarded. Is this the correct decision?

**Comment by chenziliang** [comment]
@cholick, thanks for taking a look.  Let's iterate this to see what make sense best from end user experience.

1. Could you please check the requirements in the index routing issue which wa updated by Roy ?

2. If end user uses tile, I am not worried about the invalid JSON since I assume we will hide the JSON complexity and do necessary validation. The easiest configuration is {"default_index": "main"} and there are no other routing config.

3. If we need meet the requirements of the index routing issue, there will be lots of index configuration which will confuse end user from my past previous experience. We have required "splunk-index" options, we have optional default index in index routing, we have index mapping in index routing JSON, we have null index which discard all events. 

4. I am wondering if we don't use names instead using ID, how end user configure routing for 50K applications? I was also thinking of use both ID and name. ID will be exact match and name can be regex. ID has higher priority than named when matching.

**Comment by chenziliang** [comment]
Regarding to AddAppInfo, I will can get it fixed.

**Comment by cholick** [comment]
2: "hide the JSON complexity and do necessary validation" isn't necessarily as easy as you think, depending how you package things.

Let's move the discussion for item 4 to #8 - but, in short, I think *no* config based solution scales to this. I don't think a config based solution even scales to 100 apps.

**Comment by chenziliang** [comment]
Take 2 resolves:

1. Make Splunk-index-mapping as non-required flag, if it is not setup, go to HEC default index
2. Switch to use ID of org/space/app to do index routing
3. Fix AddAppInfo. It is not required now, which means if user doesn't want app info get indexed but they still can route by org/space ID
4. Flatten all rules into one array, end user maintains the rule order or priority

**Comment by bkez322** [comment]
I would be very interested in this feature making its way into a release.

**Comment by bkez322** [comment]
For my use-case, I would definitely find filtering by `cf_org_name` `cf_space_name` to be more convenient than IDs.

Additionally, I would find it useful to be able to have filter rules that check both `cf_org_name` **and** `cf_space_name` (e.g. I only want apps running in `my-cf-space` of `my-cf-org` to go to `my-splunk-index`.  [This proposed configuration](https://github.com/cloudfoundry-community/splunk-firehose-nozzle/pull/56#issuecomment-317233550) seems to only support rules filtering by `cf_org_name` **or** `cf_space_name`.

**Comment by kashyap-splunk** [comment]
Closing this old and outdated PR. Please feel free to open a new issue/PR for the same if still needed.

**Pull request closed without merging**
