### PR TITLE
Index routing

### PR DESCRIPTION
**Pull request by cholick**
Implement a config option to route to a specific index as described in #8.

### CODE REVIEW

**Comment by cholick** [comment]
Seeing that you approved this @wjo1212, but #8 outlines a slightly changed syntax.

Do you want to branch off this work? It's probably a useful start.

Also would prefer for you to merge down. Do you need additional permissions on the repo?

**Comment by rarsan** [comment]
@zhengyuli , @wjo1212 
This feature branch is not completed and therefore not ready to be merged. Did you merge it by accident? Please refer to feature work documented in #8.

**Comment by Dontre-Splunk** [comment]
@cholick @wjo1212 Following up on the index routing work.

What state is it currently in?
Does the syntax change need to be applied and tested and then sanity tested?

**Comment by cholick** [comment]
Yes, that's 100% correct Dontre. I wrote this PR before #8 was fully fleshed out, so it doesn't match the syntax you folks came up with.

**Pull request merged**
